name: Lint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile || pnpm install

      - name: Run ESLint
        run: pnpm run lint

      - name: Run TypeScript type check
        run: npx tsc --noEmit

      - name: Check ESLint auto-fix
        run: |
          pnpm run lint --fix
          if [ -n "$(git status --porcelain)" ]; then
            echo "❌ ESLint auto-fix made changes. Please run 'pnpm run lint --fix' locally and commit the changes."
            git diff
            exit 1
          else
            echo "✅ No auto-fixable linting errors found."
          fi

      - name: Check Prettier formatting
        run: |
          if ! pnpm run format:check; then
            echo "❌ Code formatting issues found. Please run 'pnpm run format' locally."
            exit 1
          else
            echo "✅ Code formatting is correct."
          fi
